agent_name: trader
author: valory
version: 0.1.0
license: Apache-2.0
description: Trader agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiexvxghmwzokfocrlq6johtoz7dvpqm6gg6vmcapu43yjjfqc435q
  __init__.py: bafybeighcq4pmuzte6vhvvprrvo563vzghkoit2h6qdqxf2ma5bghevkee
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeib3exj2vkz4u76rc2amtwz6veeozipr6zdgzlaqsovu3dorppcina
- valory/http_client:0.23.0:bafybeieoeuy4brzimtnubmokwirhrx27ezls6cdnl5qik4rkykfle3nn2y
- valory/ipfs:0.1.0:bafybeidu3xd6rd5zysv2due2cnrc3sxx5vss2usxwaxxtxxuyha2kuhd3e
- valory/ledger:0.19.0:bafybeigfoz7d7si7s4jehvloq2zmiiocpbxcaathl3bxkyarxoerxq7g3a
- valory/p2p_libp2p_client:0.1.0:bafybeihdnfdth3qgltefgrem7xyi4b3ejzaz67xglm2hbma2rfvpl2annq
contracts:
- valory/gnosis_safe:0.1.0:bafybeih6d3vxz3jlgodxm5b2qcwsmansqj4xobuyd6hjnhzremuvd65yrm
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeid6glyjikjxmefwmhn62cxiofophegjmg2z5vqqsvk6tmyunwc274
- valory/service_registry:0.1.0:bafybeige6pubafkiqmaiyuql6pcojm6fvh5thvhrsapi53au2rhuumqymu
- valory/market_maker:0.1.0:bafybeidaz4dol7qsrwitw5jwasjtvd2vtlxhxizwkzen5kurblwacz4biu
- valory/erc20:0.1.0:bafybeid6p64a6tnovatbwybc6ocdd4u7bqkxsb4ks52rvf7ozcxxl6iaf4
- valory/multisend:0.1.0:bafybeieg4tywd5lww2vygvpkilg3hcepa4rmhehjuamyvdf6vazt554v6u
- valory/mech:0.1.0:bafybeiddc6pgurpyja2k64wzsb3jgcvl254s7rplgt5iooftsyfalqlbfq
- valory/conditional_tokens:0.1.0:bafybeigryh3d4iuyj4nruwekvurnnbzyj77flmn4vtgatwdpvbn2erpffa
- valory/realitio:0.1.0:bafybeiewpazpi2wgixmiu64kauwn7qes3xzphqid4pxvznm2himv4tciee
- valory/realitio_proxy:0.1.0:bafybeibvndq6756qck7forgeavhdbn6ykgqs2ufyg7n5g6qdfpveatxuwy
protocols:
- open_aea/signing:1.0.0:bafybeifuxs7gdg2okbn7uofymenjlmnih2wxwkym44lsgwmklgwuckxm2m
- valory/abci:0.1.0:bafybeigootsvqpk6th5xpdtzanxum3earifrrezfyhylfrit7yvqdrtgpe
- valory/acn:1.1.0:bafybeiapa5ilsobggnspoqhspftwolrx52udrwmaxdxgrk26heuvl4oooa
- valory/contract_api:1.0.0:bafybeiasywsvax45qmugus5kxogejj66c5taen27h4voriodz7rgushtqa
- valory/http:1.0.0:bafybeia5bxdua2i6chw6pg47bvoljzcpuqxzy4rdrorbdmcbnwmnfdobtu
- valory/ipfs:0.1.0:bafybeibjzhsengtxfofqpxy6syamplevp35obemwfp4c5lhag3v2bvgysa
- valory/ledger_api:1.0.0:bafybeigsvceac33asd6ecbqev34meyyjwu3rangenv6xp5rkxyz4krvcby
- valory/tendermint:0.1.0:bafybeidjqmwvgi4rqgp65tbkhmi45fwn2odr5ecezw6q47hwitsgyw4jpa
skills:
- valory/abstract_abci:0.1.0:bafybeigafjci7m7ezwzasav5xqo7v2mbxxn7qb4y7vnuc2wr2irzvn7wsy
- valory/abstract_round_abci:0.1.0:bafybeih2fyfb6kkf7r45pvdk7pyyebr5xloia4xiqxtb3qsrasnstqmepq
- valory/registration_abci:0.1.0:bafybeibndt6vxiwc2edgtaxpjbhwto3eyu33ujz3zmvtygvo2qz7xme5li
- valory/reset_pause_abci:0.1.0:bafybeigeoc363gv3wp2rrmk6p2fdxney33nxd3owtpfugzapgruwe4klyu
- valory/termination_abci:0.1.0:bafybeigqpij2sgrpnilqjljfciixop4fldq5qceixc7534q6af4potdmdm
- valory/transaction_settlement_abci:0.1.0:bafybeia7rzsbea3ch4gcafyp3z6uvqh4npws2xpdwbkkdbrqqpjops7nui
- valory/tx_settlement_multiplexer_abci:0.1.0:bafybeidj6a3arhm6wpswofka3liwdaofv5dh5x5dv2sbvgqrrnb6djdr5q
- valory/market_manager_abci:0.1.0:bafybeidnqerwkljbjgog73qaa5duu5ymsfjs6jsszeupseshx7go3n6afq
- valory/decision_maker_abci:0.1.0:bafybeienzc3c5xygb4z3l57zivtc3zexpoochjzmiil7pv646jhxrgetqm
- valory/trader_abci:0.1.0:bafybeiho45hvspxswav2zial53i3aeeq6dpb6nrpwpzltor2qphbzld26y
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.39.0.post1
  open-aea-ledger-ethereum:
    version: ==1.39.0.post1
  open-aea-test-autonomy:
    version: ==0.12.1.post4
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/trader_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      cleanup_history_depth: ${int:1}
      cleanup_history_depth_current: ${int:null}
      finalize_timeout: ${float:60.0}
      genesis_config:
        genesis_time: ${str:2022-09-26T00:00:00.000000000Z}
        chain_id: ${str:chain-c4daS1}
        consensus_params:
          block:
            max_bytes: ${str:22020096}
            max_gas: ${str:-1}
            time_iota_ms: ${str:1000}
          evidence:
            max_age_num_blocks: ${str:100000}
            max_age_duration: ${str:172800000000000}
            max_bytes: ${str:1048576}
          validator:
            pub_key_types: ${list:["ed25519"]}
          version: ${dict:{}}
        voting_power: ${str:10}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: ${int:3}
      keeper_timeout: ${float:30.0}
      max_attempts: ${int:10}
      reset_tendermint_after: ${int:2}
      retry_attempts: ${int:400}
      retry_timeout: ${int:3}
      request_retry_delay: ${float:1.0}
      request_timeout: ${float:10.0}
      service_id: ${str:trader}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_check_sleep_delay: ${int:3}
      tendermint_max_retries: ${int:5}
      tx_timeout: ${float:10.0}
      round_timeout_seconds: ${float:350.0}
      validate_timeout: ${int:1205}
      history_check_timeout: ${int:1205}
      reset_pause_duration: ${int:30}
      max_healthcheck: ${int:43200}
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      drand_public_key: ${str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      service_registry_address: ${str:null}
      agent_registry_address: ${str:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: ${int:10}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      use_termination: ${bool:false}
      on_chain_service_id: ${int:null}
      creator_per_subgraph:
        omen_subgraph: ${list:["0x89c5cc945dd550BcFfb72Fe42BfF002429F46Fec"]}
      slot_count: ${int:2}
      opening_margin: ${int:300}
      languages: ${list:["en_US"]}
      average_block_time: ${int:5}
      abt_error_mult: ${int:5}
      mech_agent_address: ${str:0xff82123dfb52ab75c417195c5fdb87630145ae81}
      bet_amount_per_threshold:
        0.0: ${int:0}
        0.1: ${int:0}
        0.2: ${int:0}
        0.3: ${int:0}
        0.4: ${int:0}
        0.5: ${int:0}
        0.6: ${int:600000000000000000}
        0.7: ${int:900000000000000000}
        0.8: ${int:1000000000000000000}
        0.9: ${int:10000000000000000000}
        1.0: ${int:100000000000000000000}
      bet_threshold: ${int:100000000000000000}
      blacklisting_duration: ${int:3600}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      prompt_template: ${str:With the given question "@{question}" and the `yes` option
        represented by `@{yes}` and the `no` option represented by `@{no}`, what are
        the respective probabilities of `p_yes` and `p_no` occurring?}
      dust_threshold: ${int:10000000000000}
      conditional_tokens_address: ${str:0xCeAfDD6bc0bEF976fdCd1112955828E00543c0Ce}
      realitio_proxy_address: ${str:0xAB16D643bA051C11962DA645f74632d3130c81E2}
      realitio_address: ${str:0x79e32aE03fb27B07C89c0c568F80287C01ca2E57}
      redeeming_batch_size: ${int:5}
      slippage: ${float:0.01}
      redeem_margin_days: ${int:15}
      policy_epsilon: ${float:0.1}
      policy_store_path: ${str:/data/}
      irrelevant_tools: ${list:["openai-text-davinci-002", "openai-text-davinci-003",
        "openai-gpt-3.5-turbo", "openai-gpt-4", "stabilityai-stable-diffusion-v1-5",
        "stabilityai-stable-diffusion-xl-beta-v2-2-2", "stabilityai-stable-diffusion-512-v2-1",
        "stabilityai-stable-diffusion-768-v2-1"]}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://host.docker.internal:8545}
      chain_id: ${int:1337}
      default_gas_price_strategy: ${str:eip1559}
      poa_chain: ${bool:false}
