agent_name: trader
author: valory
version: 0.1.0
license: Apache-2.0
description: Trader agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiexvxghmwzokfocrlq6johtoz7dvpqm6gg6vmcapu43yjjfqc435q
  __init__.py: bafybeighcq4pmuzte6vhvvprrvo563vzghkoit2h6qdqxf2ma5bghevkee
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeicksmavx23ralbdw3ajxv5fq5s4c3wzhbc3zdudefm4jqsgrg72ai
- valory/http_client:0.23.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- valory/ipfs:0.1.0:bafybeieaq56usnosbwdslmo6i2yvttwpsm6djvawsowq3jt6bkjwhw3tl4
- valory/ledger:0.19.0:bafybeig7woeog4srdby75hpjkmx4rhpkzncbf4h2pm5r6varsp26pf2uhu
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
- valory/http_server:0.22.0:bafybeihpgu56ovmq4npazdbh6y6ru5i7zuv6wvdglpxavsckyih56smu7m
contracts:
- valory/gnosis_safe:0.1.0:bafybeidcb25wneezfd2iaiqa7ygxlimwwacvycahhenvpw7tdvwdigllzm
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeidwwhkqin3zchbjl7ro6n3tj5kwbfhfvmrdpuxn7owy3b4ktrluba
- valory/service_registry:0.1.0:bafybeiekytropd5ysnap2wkekub3byi5jbda3qll7awchvhu5plbpafhmi
- valory/market_maker:0.1.0:bafybeiba25nt26ntjzkkpfyl2ngbjxrfd44ckg3znfhqm552725vb3gaka
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- valory/mech:0.1.0:bafybeidwpijhdwj5abewa44k3tzxuanxykzmgnnffeq7re2rxp7pqbd2ou
- valory/conditional_tokens:0.1.0:bafybeibnzmqmeph4cj5vfh3s622mo2o5627vjjwc6bptrhj4dk65mzgvhe
- valory/realitio:0.1.0:bafybeietgux6kkhdquspy35qera7gjwwqwrremmoeatjzwwokjb2lzsata
- valory/realitio_proxy:0.1.0:bafybeidx37xzjjmapwacedgzhum6grfzhp5vhouz4zu3pvpgdy5pgb2fr4
- valory/agent_registry:0.1.0:bafybeifsb2krg4qnr4nxdrhcdgpncfr5ra2nahebvn2f2yff7ebwe7ooae
- valory/service_staking_token:0.1.0:bafybeieyfto5xwmvxiu52qxxudp2zaa22idrvw3jr6bytbok6bg3nylgqi
- valory/transfer_nft_condition:0.1.0:bafybeihnict3irtvnyxtkwyg6wphe44wz3dogijiha45xrkcrh5ktq2lsi
- valory/erc20:0.1.0:bafybeia7a7mfjeok4ywpmejz74msofagagcentsudqxfojadmxlur5qolu
- valory/staking_token:0.1.0:bafybeig4fl35dn7d5gnprux2nwsqbirm7zkiujz3xvrwcjuktz6hkq4as4
- valory/mech_activity:0.1.0:bafybeiec6nnvfs6captlncrtjfygpp275vkfajvj4frrnab7thsca6337e
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- valory/abstract_abci:0.1.0:bafybeieh4ei3qdelmacnm7vwq57phoewgumr3udvxt6pybmuggwc3yk65q
- valory/abstract_round_abci:0.1.0:bafybeiar2yhzxacfe3qqamqhaihtlcimquwedffctw55sowx6rac3cm3ui
- valory/registration_abci:0.1.0:bafybeieu7vq3pyns4t5ty6u3sbmpkd7yznpg3rmqifoz3jhy7pmqyg3w6q
- valory/reset_pause_abci:0.1.0:bafybeiameewywqigpupy3u2iwnkfczeiiucue74x2l5lbge74rmw6bgaie
- valory/termination_abci:0.1.0:bafybeif2zim2de356eo3sipkmoev5emwadpqqzk3huwqarywh4tmqt3vzq
- valory/transaction_settlement_abci:0.1.0:bafybeic3tccdjypuge2lewtlgprwkbb53lhgsgn7oiwzyrcrrptrbeyote
- valory/tx_settlement_multiplexer_abci:0.1.0:bafybeibgzwhazshodynrpsowbnvy7awtl6vgzrf3yunvicgrha4hfzbsi4
- valory/market_manager_abci:0.1.0:bafybeicymkyk7e5rohauml6xazai6mv2rqd3euz3ifbk2ftfkylhpgo4ra
- valory/decision_maker_abci:0.1.0:bafybeicr3o4z5ytp6njmsxlj3p6cbaxyad6tdv5kyoxaeon5da2wn6hxqy
- valory/trader_abci:0.1.0:bafybeigpelxc6kppckpx4phewwyi24mejyz54fi6g5i7swnm3xi2x5olve
- valory/staking_abci:0.1.0:bafybeiduborfqevheegy3plk7bzhkl4fukwixvlb57tenijdepintubbdi
- valory/check_stop_trading_abci:0.1.0:bafybeiat5hmo6i2r6t6ufyfnidvepixmbnppotdmztu4dad5j4hiewdh64
- valory/mech_interact_abci:0.1.0:bafybeih2cck5xu6yaibomwtm5zbcp6llghr3ighdnk56fzwu3ihu5xx35e
customs:
- valory/mike_strat:0.1.0:bafybeihjiol7f4ch4piwfikurdtfwzsh6qydkbsztpbwbwb2yrqdqf726m
- valory/bet_amount_per_threshold:0.1.0:bafybeihufqu2ra7vud4h6g2nwahx7mvdido7ff6prwnib2tdlc4np7dw24
- valory/kelly_criterion_no_conf:0.1.0:bafybeibxfp27rzrfnp7sxq62vwv32pdvrijxi7vzg7ihukkaka3bwzrgae
- w1kke/always_blue:0.1.0:bafybeieshu32h3es2fslduuhr7nimuvh2vuibyeqdunzrcggaeohekg3jm
- jhehemann/kelly_criterion:0.1.0:bafybeif55cu7cf6znyma7kxus4wxa2doarhau2xmndo57iegshxorivwmq
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.52.0
  open-aea-ledger-ethereum:
    version: ==1.52.0
  open-aea-test-autonomy:
    version: ==0.14.12
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/trader_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      cleanup_history_depth: ${int:1}
      cleanup_history_depth_current: ${int:null}
      finalize_timeout: ${float:60.0}
      genesis_config:
        genesis_time: ${str:2022-09-26T00:00:00.000000000Z}
        chain_id: ${str:chain-c4daS1}
        consensus_params:
          block:
            max_bytes: ${str:22020096}
            max_gas: ${str:-1}
            time_iota_ms: ${str:1000}
          evidence:
            max_age_num_blocks: ${str:100000}
            max_age_duration: ${str:172800000000000}
            max_bytes: ${str:1048576}
          validator:
            pub_key_types: ${list:["ed25519"]}
          version: ${dict:{}}
        voting_power: ${str:10}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: ${int:3}
      keeper_timeout: ${float:30.0}
      max_attempts: ${int:10}
      reset_tendermint_after: ${int:2}
      retry_attempts: ${int:400}
      retry_timeout: ${int:3}
      request_retry_delay: ${float:1.0}
      request_timeout: ${float:10.0}
      service_id: ${str:trader}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_check_sleep_delay: ${int:3}
      tendermint_max_retries: ${int:5}
      tx_timeout: ${float:10.0}
      round_timeout_seconds: ${float:350.0}
      validate_timeout: ${int:1205}
      history_check_timeout: ${int:1205}
      reset_pause_duration: ${int:30}
      max_healthcheck: ${int:43200}
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      multisend_batch_size: ${int:1}
      drand_public_key: ${str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      service_registry_address: ${str:null}
      agent_registry_address: ${str:0xE49CB081e8d96920C38aA7AB90cb0294ab4Bc8EA}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: ${int:10}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      termination_from_block: ${int:0}
      use_termination: ${bool:false}
      on_chain_service_id: ${int:null}
      creator_per_subgraph:
        omen_subgraph: ${list:["0x89c5cc945dd550BcFfb72Fe42BfF002429F46Fec"]}
      slot_count: ${int:2}
      opening_margin: ${int:300}
      languages: ${list:["en_US"]}
      average_block_time: ${int:5}
      abt_error_mult: ${int:5}
      the_graph_error_message_key: ${str:message}
      the_graph_payment_required_error: ${str:payment required for subsequent requests
        for this API key}
      mech_contract_address: ${str:0x77af31De935740567Cf4fF1986D04B2c964A786a}
      mech_request_price: ${int:null}
      mech_chain_id: ${str:gnosis}
      mech_activity_checker_contract: ${str:0x0000000000000000000000000000000000000000}
      mech_wrapped_native_token_address: ${str:0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d}
      sample_bets_closing_days: ${int:10}
      trading_strategy: ${str:kelly_criterion_no_conf}
      use_fallback_strategy: ${bool:true}
      bet_threshold: ${int:100000000000000000}
      blacklisting_duration: ${int:3600}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      tools_accuracy_hash: ${str:QmR8etyW3TPFadNtNrW54vfnFqmh8vBrMARWV76EmxCZyk}
      prompt_template: ${str:With the given question "@{question}" and the `yes` option
        represented by `@{yes}` and the `no` option represented by `@{no}`, what are
        the respective probabilities of `p_yes` and `p_no` occurring?}
      dust_threshold: ${int:10000000000000}
      conditional_tokens_address: ${str:0xCeAfDD6bc0bEF976fdCd1112955828E00543c0Ce}
      realitio_proxy_address: ${str:0xAB16D643bA051C11962DA645f74632d3130c81E2}
      realitio_address: ${str:0x79e32aE03fb27B07C89c0c568F80287C01ca2E57}
      event_filtering_batch_size: ${int:5000}
      reduce_factor: ${float:0.25}
      minimum_batch_size: ${int:500}
      use_subgraph_for_redeeming: ${bool:true}
      max_filtering_retries: ${int:6}
      redeeming_batch_size: ${int:5}
      slippage: ${float:0.01}
      redeem_round_timeout: ${float:3600.0}
      policy_epsilon: ${float:0.1}
      store_path: ${str:/data/}
      irrelevant_tools: ${list:["openai-text-davinci-002", "openai-text-davinci-003",
        "openai-gpt-3.5-turbo", "openai-gpt-4", "stabilityai-stable-diffusion-v1-5",
        "stabilityai-stable-diffusion-xl-beta-v2-2-2", "stabilityai-stable-diffusion-512-v2-1",
        "stabilityai-stable-diffusion-768-v2-1"]}
      use_nevermined: ${bool:true}
      mech_to_subscription_params: ${list:[["base_url", "https://marketplace-api.gnosis.nevermined.app/api/v1/metadata/assets/ddo"],
        ["did", "did:nv:01706149da2f9f3f67cf79ec86c37d63cec87fc148f5633b12bf6695653d5b3c"],
        ["escrow_payment_condition_address", "0x31B2D187d674C9ACBD2b25f6EDce3d2Db2B7f446"],
        ["lock_payment_condition_address", "0x2749DDEd394196835199471027713773736bffF2"],
        ["transfer_nft_condition_address", "0x659fCA7436936e9fe8383831b65B8B442eFc8Ea8"],
        ["token_address", "0x1b5DeaD7309b56ca7663b3301A503e077Be18cba"], ["order_address",
        "0x72201948087aE83f8Eac22cf7A9f2139e4cFA829"], ["nft_amount", "100"], ["payment_token",
        "0x0000000000000000000000000000000000000000"], ["order_address", "0x72201948087aE83f8Eac22cf7A9f2139e4cFA829"],
        ["price", "1000000000000000000"]]}
      staking_contract_address: ${str:0x2Ef503950Be67a98746F484DA0bBAdA339DF3326}
      staking_interaction_sleep_time: ${int:5}
      disable_trading: ${bool:false}
      stop_trading_if_staking_kpi_met: ${bool:true}
      agent_balance_threshold: ${int:10000000000000000}
      refill_check_interval: ${int:10}
      tool_punishment_multiplier: ${int:1}
      contract_timeout: ${float:300.0}
      file_hash_to_strategies_json: ${list:[["bafybeihufqu2ra7vud4h6g2nwahx7mvdido7ff6prwnib2tdlc4np7dw24",["bet_amount_per_threshold"]],["bafybeibxfp27rzrfnp7sxq62vwv32pdvrijxi7vzg7ihukkaka3bwzrgae",["kelly_criterion_no_conf"]]]}
      strategies_kwargs: ${list:[["bet_kelly_fraction",1.0],["floor_balance",500000000000000000],["bet_amount_per_threshold",{"0.0":0,"0.1":0,"0.2":0,"0.3":0,"0.4":0,"0.5":0,"0.6":60000000000000000,"0.7":90000000000000000,"0.8":100000000000000000,"0.9":1000000000000000000,"1.0":10000000000000000000}]]}
      service_endpoint: ${str:https://trader.staging.autonolas.tech/}
      rpc_sleep_time: ${int:10}
      mech_interaction_sleep_time: ${int:10}
  benchmarking_mode:
    args:
      enabled: ${bool:false}
      native_balance: ${int:10000000000000000000}
      collateral_balance: ${int:10000000000000000000}
      mech_cost: ${int:10000000000000000}
      pool_fee: ${int:20000000000000000}
      outcome_token_amounts: ${list:[11000000000000000000,9000000000000000000]}
      outcome_token_marginal_prices: ${list:[0.4,0.6]}
      sep: ${str:,}
      dataset_filename: ${str:benchmark_data.csv}
      question_field: ${str:question}
      question_id_field: ${str:question_id}
      answer_field: ${str:answer}
      p_yes_field_part: ${str:p_yes_}
      p_no_field_part: ${str:p_no_}
      confidence_field_part: ${str:confidence_}
      part_prefix_mode: ${bool:true}
      bet_amount_field: ${str:collateral_amount}
      results_filename: ${str:benchmarking_results.csv}
      randomness: ${str:benchmarking_randomness}
  acc_info_fields:
    args:
      tool: ${str:tool}
      requests: ${str:total_requests}
      accuracy: ${str:tool_accuracy}
      sep: ${str:,}
  network_subgraph:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      response_key: ${str:data:blocks}
      response_index: ${int:0}
      response_type: ${str:dict}
      error_key: ${str:errors}
      error_index: ${int:0}
      error_type: ${str:dict}
      retries: ${int:5}
      url: ${str:https://api.thegraph.com/subgraphs/name/stakewise/ethereum-gnosis}
  omen_subgraph:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      response_key: ${str:data:fixedProductMarketMakers}
      response_type: ${str:list}
      error_key: ${str:errors}
      error_index: ${int:0}
      error_type: ${str:dict}
      retries: ${int:5}
      url: ${str:https://api.thegraph.com/subgraphs/name/protofire/omen-xdai}
  randomness_api:
    args:
      method: ${str:GET}
      response_key: ${str:null}
      response_type: ${str:dict}
      retries: ${int:5}
      url: ${str:https://drand.cloudflare.com/public/latest}
  mech_response:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:GET}
      response_key: ${str:result}
      response_type: ${str:str}
      retries: ${int:5}
      url: ${str:''}
  agent_tools:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:GET}
      response_key: ${str:tools}
      response_type: ${str:list}
      retries: ${int:5}
      url: ${str:''}
  trades_subgraph:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      response_key: ${str:data:fpmmTrades}
      response_type: ${str:list}
      error_key: ${str:errors}
      error_index: ${int:0}
      error_type: ${str:dict}
      retries: ${int:5}
      url: ${str:https://api.thegraph.com/subgraphs/name/protofire/omen-xdai}
  conditional_tokens_subgraph:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      response_key: ${str:data:user:userPositions}
      response_type: ${str:list}
      error_key: ${str:errors}
      error_index: ${int:0}
      error_type: ${str:dict}
      retries: ${int:5}
      url: ${str:https://api.thegraph.com/subgraphs/name/gnosis/conditional-tokens-gc}
  realitio_subgraph:
    args:
      headers:
        Content-Type: ${str:application/json}
      method: ${str:POST}
      response_key: ${str:data:answers}
      response_type: ${str:list}
      error_key: ${str:errors}
      error_index: ${int:0}
      error_type: ${str:dict}
      retries: ${int:5}
      url: ${str:https://api.thegraph.com/subgraphs/name/realityeth/realityeth-gnosis}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://host.docker.internal:8545}
      chain_id: ${int:1337}
      default_gas_price_strategy: ${str:eip1559}
      poa_chain: ${bool:false}
    gnosis:
      address: ${str:https://rpc.gnosischain.com}
      chain_id: ${int:100}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: ${str:0.0.0.0}
  port: ${int:8716}
  target_skill_id: valory/trader_abci:0.1.0
