agent_name: trader
author: valory
version: 0.1.0
license: Apache-2.0
description: Trader agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiexvxghmwzokfocrlq6johtoz7dvpqm6gg6vmcapu43yjjfqc435q
  __init__.py: bafybeighcq4pmuzte6vhvvprrvo563vzghkoit2h6qdqxf2ma5bghevkee
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeifr35jcajq2lqnj2rd5lueo4g5nysbvbaacdchfecwgtcojqx3mie
- valory/http_client:0.23.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- valory/ipfs:0.1.0:bafybeigcijdbwgdekow5c2ikeltetoteabfp52ewy3xfkd7ygaqbl7j3ke
- valory/ledger:0.19.0:bafybeig7woeog4srdby75hpjkmx4rhpkzncbf4h2pm5r6varsp26pf2uhu
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
- valory/http_server:0.22.0:bafybeihpgu56ovmq4npazdbh6y6ru5i7zuv6wvdglpxavsckyih56smu7m
contracts:
- valory/gnosis_safe:0.1.0:bafybeibbglwlfvytwcphk6pccdbzubpfh2hmmi2me35bxzic32cepectje
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeibkdn73yvpkuwm3holsunklhzdnuwunhebrwnxkxq25liq36ect4m
- valory/service_registry:0.1.0:bafybeih4ao44fkkrdofzcf6d2oem6tx4pjo6g27ang5junmcwtw3w4tyra
- valory/market_maker:0.1.0:bafybeichjutxliu4cmkiwlxj6hifvlbfwe2lgouphwdocpeml45w6dfjkq
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- valory/mech:0.1.0:bafybeiejfjfoxqggghcme43sx53q5gruefrws3k2jam2opkxl5uzffoarm
- valory/conditional_tokens:0.1.0:bafybeigucumqbsk74nj4rpm4p2cpiky4dj6uws7nfmgpimuviaxcamwqnu
- valory/realitio:0.1.0:bafybeic5ie4oodetj4krdogydvbfxg4qggc3matpiflocah626tpevpreq
- valory/realitio_proxy:0.1.0:bafybeidx37xzjjmapwacedgzhum6grfzhp5vhouz4zu3pvpgdy5pgb2fr4
- valory/agent_registry:0.1.0:bafybeidvylp5mxb5fwhql7ktrxaeaohjy3qgj4cbbdnjwl2mxxh5jgqxjm
- valory/service_staking_token:0.1.0:bafybeifpjyyqdt6lkuajaazucp4cvg2ydcfzblr2wen626ubdtmaiven5y
- valory/transfer_nft_condition:0.1.0:bafybeifb3tby6qs4veaf4nhmecfhl2xxbmh5huuptfod4kbnj6ngj3i4wi
- valory/erc20:0.1.0:bafybeih3y7k76wjugbbz7bfhxix24cq33m63emjhfog2r5qajn3bgtbb2y
- valory/relayer:0.1.0:bafybeicawmds6czx7db2lcktvexwrp245jpekgulndtos5s5zdid3ilvq4
protocols:
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- valory/abstract_abci:0.1.0:bafybeibzxex6md6xp5eibvp23cmkk7xgdyd44r5lxhfhlquwe3nb22ujgy
- valory/abstract_round_abci:0.1.0:bafybeih2soag6gy472x7vbbxmetmr532jqzm2efcapymi3725as33fvjvu
- valory/registration_abci:0.1.0:bafybeiaxomjnv2h7ozc7mvmz5wysfinfgtqnniznpcdunijb5iiekv4mzi
- valory/reset_pause_abci:0.1.0:bafybeiatyhxriq2gzny3s5by2plk7tyw4o5uvabzuhvhvwrl2pburbdjcm
- valory/termination_abci:0.1.0:bafybeig3gpsgm4c2ibywmriv2py6224xxsfw5b6p6j3gc7szz3qv22bhce
- valory/transaction_settlement_abci:0.1.0:bafybeicq4ttsarwurbll4xqabjb26g3po2ntrcxkwi7vac6d2kmvt6hati
- valory/tx_settlement_multiplexer_abci:0.1.0:bafybeidpeaxcey6vhiu2maz6wo5tg76kvrpiq5mpy5w5kf4yn66pri5qj4
- valory/market_manager_abci:0.1.0:bafybeiccbsrg3knbkax6nyqesn5u67ji6rwylvlgut7cap254sk5hyvojq
- valory/decision_maker_abci:0.1.0:bafybeibeci66bopuq2n4tketevhzgxnc2o2sj6xva67oz5z4r745js5iqe
- valory/trader_abci:0.1.0:bafybeieziwtxhzliuksgvsklij4rg2hwldctuk6zlhzbktlm2gdtj7ytr4
- valory/staking_abci:0.1.0:bafybeielq2a5ogbee5z4mnaqhzfcdc6uzo35vt64lt2cjnpx4om7j54n4u
- valory/check_stop_trading_abci:0.1.0:bafybeie5owp3bbwm3aogxrg6qhrbgu4r34p7qlf2xyc7ywlfgkp2ejl7eq
- valory/mech_interact_abci:0.1.0:bafybeicj4c6brjtijdqywn3knejwl4o5ynzi4jcc4sinezeyj7lbgxbu5q
customs:
- valory/mike_strat:0.1.0:bafybeihjiol7f4ch4piwfikurdtfwzsh6qydkbsztpbwbwb2yrqdqf726m
- valory/bet_amount_per_threshold:0.1.0:bafybeihufqu2ra7vud4h6g2nwahx7mvdido7ff6prwnib2tdlc4np7dw24
- w1kke/always_blue:0.1.0:bafybeieshu32h3es2fslduuhr7nimuvh2vuibyeqdunzrcggaeohekg3jm
- jhehemann/kelly_criterion:0.1.0:bafybeif55cu7cf6znyma7kxus4wxa2doarhau2xmndo57iegshxorivwmq
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.53.0
  open-aea-ledger-ethereum:
    version: ==1.53.0
  open-aea-test-autonomy:
    version: ==0.14.14
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/trader_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      cleanup_history_depth: ${int:1}
      cleanup_history_depth_current: ${int:null}
      finalize_timeout: ${float:60.0}
      genesis_config:
        genesis_time: ${str:2022-09-26T00:00:00.000000000Z}
        chain_id: ${str:chain-c4daS1}
        consensus_params:
          block:
            max_bytes: ${str:22020096}
            max_gas: ${str:-1}
            time_iota_ms: ${str:1000}
          evidence:
            max_age_num_blocks: ${str:100000}
            max_age_duration: ${str:172800000000000}
            max_bytes: ${str:1048576}
          validator:
            pub_key_types: ${list:["ed25519"]}
          version: ${dict:{}}
        voting_power: ${str:10}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: ${int:3}
      keeper_timeout: ${float:30.0}
      max_attempts: ${int:10}
      reset_tendermint_after: ${int:2}
      retry_attempts: ${int:400}
      retry_timeout: ${int:3}
      request_retry_delay: ${float:1.0}
      request_timeout: ${float:10.0}
      service_id: ${str:trader}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_check_sleep_delay: ${int:3}
      tendermint_max_retries: ${int:5}
      tx_timeout: ${float:10.0}
      round_timeout_seconds: ${float:350.0}
      validate_timeout: ${int:1205}
      history_check_timeout: ${int:1205}
      reset_pause_duration: ${int:30}
      max_healthcheck: ${int:43200}
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      multisend_batch_size: ${int:1}
      drand_public_key: ${str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      service_registry_address: ${str:null}
      agent_registry_address: ${str:0xE49CB081e8d96920C38aA7AB90cb0294ab4Bc8EA}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: ${int:10}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      termination_from_block: ${int:0}
      use_termination: ${bool:false}
      on_chain_service_id: ${int:null}
      creator_per_subgraph:
        omen_subgraph: ${list:["0x89c5cc945dd550BcFfb72Fe42BfF002429F46Fec"]}
      slot_count: ${int:2}
      opening_margin: ${int:300}
      languages: ${list:["en_US"]}
      average_block_time: ${int:5}
      abt_error_mult: ${int:5}
      mech_contract_address: ${str:0x77af31De935740567Cf4fF1986D04B2c964A786a}
      mech_request_price: ${int:null}
      mech_chain_id: ${str:gnosis}
      mech_wrapped_native_token_address: ${str:0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d}
      sample_bets_closing_days: ${int:10}
      trading_strategy: ${str:kelly_criterion}
      use_fallback_strategy: ${bool:true}
      bet_threshold: ${int:100000000000000000}
      blacklisting_duration: ${int:3600}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      prompt_template: ${str:With the given question "@{question}" and the `yes` option
        represented by `@{yes}` and the `no` option represented by `@{no}`, what are
        the respective probabilities of `p_yes` and `p_no` occurring?}
      dust_threshold: ${int:10000000000000}
      conditional_tokens_address: ${str:0xCeAfDD6bc0bEF976fdCd1112955828E00543c0Ce}
      realitio_proxy_address: ${str:0xAB16D643bA051C11962DA645f74632d3130c81E2}
      realitio_address: ${str:0x79e32aE03fb27B07C89c0c568F80287C01ca2E57}
      event_filtering_batch_size: ${int:5000}
      reduce_factor: ${float:0.25}
      minimum_batch_size: ${int:500}
      use_subgraph_for_redeeming: ${bool:true}
      max_filtering_retries: ${int:6}
      redeeming_batch_size: ${int:5}
      slippage: ${float:0.01}
      redeem_round_timeout: ${float:3600.0}
      policy_epsilon: ${float:0.1}
      store_path: ${str:/data/}
      irrelevant_tools: ${list:["openai-text-davinci-002", "openai-text-davinci-003",
        "openai-gpt-3.5-turbo", "openai-gpt-4", "stabilityai-stable-diffusion-v1-5",
        "stabilityai-stable-diffusion-xl-beta-v2-2-2", "stabilityai-stable-diffusion-512-v2-1",
        "stabilityai-stable-diffusion-768-v2-1"]}
      use_nevermined: ${bool:true}
      mech_to_subscription_params: ${list:[["base_url", "https://marketplace-api.gnosis.nevermined.app/api/v1/metadata/assets/ddo"],
        ["did", "did:nv:0ea01d5de3b34e3792db825f2a5f5595c393c68b19fd5efdacd00fcc63a53483"],
        ["escrow_payment_condition_address", "0x9dDC4F1Ea5b94C138A23b60EC48c0d01d172629a"],
        ["lock_payment_condition_address", "0xDE85A368Ee6f374d236500d176814365370778dA"],
        ["transfer_nft_condition_address", "0xbBa4A25262745a55f020D0a3E9a82c25bb6F4979"],
        ["token_address", "0x80A9b55F8604acC26dF2Ac6e07F9dC5B0eAa05Ce"], ["order_address",
        "0xc7751eff5396a846e7bc83ac31d3cb7d37cb49e4"], ["nft_amount", "100"], ["payment_token",
        "0x0000000000000000000000000000000000000000"], ["order_address", "0xc7751eff5396a846e7bc83ac31d3cb7d37cb49e4"],
        ["price", "1000000000000000000"]]}
      staking_contract_address: ${str:0x2Ef503950Be67a98746F484DA0bBAdA339DF3326}
      staking_interaction_sleep_time: ${int:5}
      disable_trading: ${bool:false}
      stop_trading_if_staking_kpi_met: ${bool:true}
      agent_balance_threshold: ${int:10000000000000000}
      refill_check_interval: ${int:10}
      tool_punishment_multiplier: ${int:1}
      contract_timeout: ${float:300.0}
      file_hash_to_strategies_json: ${list:[["bafybeihufqu2ra7vud4h6g2nwahx7mvdido7ff6prwnib2tdlc4np7dw24",["bet_amount_per_threshold"]],["bafybeif55cu7cf6znyma7kxus4wxa2doarhau2xmndo57iegshxorivwmq",["kelly_criterion"]]]}
      strategies_kwargs: ${list:[["bet_kelly_fraction",0.5],["floor_balance",500000000000000000],["bet_amount_per_threshold",{"0.0":0,"0.1":0,"0.2":0,"0.3":0,"0.4":0,"0.5":0,"0.6":60000000000000000,"0.7":90000000000000000,"0.8":100000000000000000,"0.9":1000000000000000000,"1.0":10000000000000000000}]]}
      service_endpoint: ${str:https://trader.staging.autonolas.tech/}
      rpc_sleep_time: ${int:10}
      mech_interaction_sleep_time: ${int:10}
  benchmarking_mode:
    args:
      enabled: ${bool:false}
      native_balance: ${int:10000000000000000000}
      collateral_balance: ${int:10000000000000000000}
      mech_cost: ${int:10000000000000000}
      pool_fee: ${int:20000000000000000}
      outcome_token_amounts: ${list:[11000000000000000000,9000000000000000000]}
      outcome_token_marginal_prices: ${list:[0.4,0.6]}
      sep: ${str:,}
      dataset_filename: ${str:benchmark_data.csv}
      question_field: ${str:question}
      question_id_field: ${str:question_id}
      answer_field: ${str:answer}
      p_yes_field_part: ${str:p_yes_}
      p_no_field_part: ${str:p_no_}
      confidence_field_part: ${str:confidence_}
      part_prefix_mode: ${bool:true}
      bet_amount_field: ${str:collateral_amount}
      results_filename: ${str:benchmarking_results.csv}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://host.docker.internal:8545}
      chain_id: ${int:1337}
      default_gas_price_strategy: ${str:eip1559}
      poa_chain: ${bool:false}
    gnosis:
      address: ${str:https://rpc.gnosischain.com}
      chain_id: ${int:100}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: ${str:0.0.0.0}
  target_skill_id: valory/trader_abci:0.1.0
