agent_name: trader
author: valory
version: 0.1.0
license: Apache-2.0
description: Trader agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiexvxghmwzokfocrlq6johtoz7dvpqm6gg6vmcapu43yjjfqc435q
  __init__.py: bafybeighcq4pmuzte6vhvvprrvo563vzghkoit2h6qdqxf2ma5bghevkee
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeifq54kwhrbrzalzn2jt6qm5ntzck7z23hgm2jmewfgxs4jsnhu5vu
- valory/http_client:0.23.0:bafybeieoeuy4brzimtnubmokwirhrx27ezls6cdnl5qik4rkykfle3nn2y
- valory/ipfs:0.1.0:bafybeicwe4fksbhaqs4qycfdqbzgqtikfn3u4g5y5fucxfmriezwwf7hse
- valory/ledger:0.19.0:bafybeiejc7g7ebv3cleiqb4f4h4pspcu6vtr54332szwlqiabfs3sfdh44
- valory/p2p_libp2p_client:0.1.0:bafybeihdnfdth3qgltefgrem7xyi4b3ejzaz67xglm2hbma2rfvpl2annq
contracts:
- valory/gnosis_safe:0.1.0:bafybeifvkqw4whvdqm2pibwqfsd4ae2q4x2zv7e2gcg4iya45xw2qf7mb4
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeicyu6zsgu73sfr6mzg5fse2ypcrvsgqacy3fvkx3ynw7i5eykha3a
- valory/service_registry:0.1.0:bafybeie3ncxiovdz74w3vsyatukzp2e2dsuetousaz6gzkfnym5muzisku
- valory/market_maker:0.1.0:bafybeiarescyof4pt4wofvvs7ef2afumalhthhtimypquyge3njqeiwtee
- valory/erc20:0.1.0:bafybeihucgrojjrgyvweuwtjx3x6fnumt55iit22n2wfptvebwzgug7etq
- valory/multisend:0.1.0:bafybeict2k3vf3c4fvzosaq5kku2ivtzsskbomrujmmoicut7eg52onnje
- valory/mech:0.1.0:bafybeib3syh35usqjtqapqjjvobnkcxllkpjbxcb67g3vp3f566qsbhqgq
protocols:
- open_aea/signing:1.0.0:bafybeifuxs7gdg2okbn7uofymenjlmnih2wxwkym44lsgwmklgwuckxm2m
- valory/abci:0.1.0:bafybeigootsvqpk6th5xpdtzanxum3earifrrezfyhylfrit7yvqdrtgpe
- valory/acn:1.1.0:bafybeiapa5ilsobggnspoqhspftwolrx52udrwmaxdxgrk26heuvl4oooa
- valory/contract_api:1.0.0:bafybeiasywsvax45qmugus5kxogejj66c5taen27h4voriodz7rgushtqa
- valory/http:1.0.0:bafybeia5bxdua2i6chw6pg47bvoljzcpuqxzy4rdrorbdmcbnwmnfdobtu
- valory/ipfs:0.1.0:bafybeibjzhsengtxfofqpxy6syamplevp35obemwfp4c5lhag3v2bvgysa
- valory/ledger_api:1.0.0:bafybeigsvceac33asd6ecbqev34meyyjwu3rangenv6xp5rkxyz4krvcby
- valory/tendermint:0.1.0:bafybeidjqmwvgi4rqgp65tbkhmi45fwn2odr5ecezw6q47hwitsgyw4jpa
skills:
- valory/abstract_abci:0.1.0:bafybeidnoe2d2ibt75smtc4m4ukklj62qqnefhclbvekhj54mz4ti5lgda
- valory/abstract_round_abci:0.1.0:bafybeibjbnxjqqiel4f4niw242vzbrjvw4252fv5rul47ut5a2b3drrrua
- valory/registration_abci:0.1.0:bafybeigta5ynlmxkzjwvzhg67wrrvmdqgtc4y3uyayzrzqhh5uusuhpu7e
- valory/reset_pause_abci:0.1.0:bafybeifygg43xswd3e6vya4l4vnx25hubsxrp5ms7uf2zr4dnh6j7ncqci
- valory/termination_abci:0.1.0:bafybeidkip3dcol7uqk6tuaggxc4mvlw6nvcge45krkfitzg7tzmnnqc3a
- valory/transaction_settlement_abci:0.1.0:bafybeia5qamp7a6vkgoi6mrdeitoa232celqcmwwitof562kveizrs4ebm
- valory/tx_settlement_multiplexer_abci:0.1.0:bafybeicjm5s3ojwucxabouqfs3giqfbj5vwtjqe3i5harqc4vq4vjq2v4u
- valory/market_manager_abci:0.1.0:bafybeibx6wpxk2qvzgzrunih55hazrggfqmkuqo4orhp6lgqynu6uamch4
- valory/decision_maker_abci:0.1.0:bafybeibkdb4thdcpkciyfopw22zplvmnm5wmjk3kci5rjh7tl7cgp4oe54
- valory/trader_abci:0.1.0:bafybeib3553fpad7mxmr4wppyzt2u6m557t54s6udqjqfkk2nqkt53aasa
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.37.0
  open-aea-ledger-ethereum:
    version: ==1.37.0
  open-aea-test-autonomy:
    version: ==0.10.11.post1
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/trader_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/trader_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
      cleanup_history_depth: ${int:1}
      cleanup_history_depth_current: ${int:null}
      finalize_timeout: ${float:60.0}
      genesis_config:
        genesis_time: ${str:2022-09-26T00:00:00.000000000Z}
        chain_id: ${str:chain-c4daS1}
        consensus_params:
          block:
            max_bytes: ${str:22020096}
            max_gas: ${str:-1}
            time_iota_ms: ${str:1000}
          evidence:
            max_age_num_blocks: ${str:100000}
            max_age_duration: ${str:172800000000000}
            max_bytes: ${str:1048576}
          validator:
            pub_key_types: ${list:["ed25519"]}
          version: ${dict:{}}
        voting_power: ${str:10}
      init_fallback_gas: ${int:0}
      keeper_allowed_retries: ${int:3}
      keeper_timeout: ${float:30.0}
      max_attempts: ${int:10}
      reset_tendermint_after: ${int:2}
      retry_attempts: ${int:400}
      retry_timeout: ${int:3}
      request_retry_delay: ${float:1.0}
      request_timeout: ${float:10.0}
      service_id: ${str:trader}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_check_sleep_delay: ${int:3}
      tendermint_max_retries: ${int:5}
      tx_timeout: ${float:10.0}
      round_timeout_seconds: ${float:350.0}
      validate_timeout: ${int:1205}
      history_check_timeout: ${int:1205}
      reset_pause_duration: ${int:30}
      max_healthcheck: ${int:43200}
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      drand_public_key: ${str:868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31}
      service_registry_address: ${str:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: ${int:10}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      use_termination: ${bool:false}
      on_chain_service_id: ${int:null}
      creator_per_subgraph:
        omen_subgraph: ${list:["0x89c5cc945dd550BcFfb72Fe42BfF002429F46Fec"]}
      slot_count: ${int:2}
      opening_margin: ${int:300}
      languages: ${list:["en_US"]}
      mech_agent_address: ${str:0xff82123dfb52ab75c417195c5fdb87630145ae81}
      mech_tool: ${str:prediction-online}
      bet_amount_per_threshold:
        0.0: ${int:0}
        0.1: ${int:0}
        0.2: ${int:0}
        0.3: ${int:0}
        0.4: ${int:0}
        0.5: ${int:0}
        0.6: ${int:600000000000000000}
        0.7: ${int:900000000000000000}
        0.8: ${int:1000000000000000000}
        0.9: ${int:10000000000000000000}
        1.0: ${int:100000000000000000000}
      bet_threshold: ${int:100000000000000000}
      blacklisting_duration: ${int:3600}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      prompt_template: ${str:With the given question "@{question}" and the `yes` option
        represented by `@{yes}` and the `no` option represented by `@{no}`, what are
        the respective probabilities of `p_yes` and `p_no` occurring?}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://host.docker.internal:8545}
      chain_id: ${int:1337}
      default_gas_price_strategy: ${str:eip1559}
      poa_chain: ${bool:false}
